# auto generated by srcgen healthEvents 11/17/2020 2:22:05 PM 
# modified nov 20 with custom code for query strings.

<#
    .DESCRIPTION
    /v1/healthEvents,get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER limit
    rows to return max 1000

    .PARAMETER token
    Continuation token to get the next page of results. A page object with the next continuation token is returned in the response body. Subsequent GET requests should specify the continuation token to get the next page of results

    .OUTPUTS
    PSCustomObject.
#>


function Get-HealthEvents {

    Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter()][string] $limit,
        [parameter()][string] $token
    )
    $params = @{}
    if ($limit) {
        $params['limit'] = $limit
    }
    if ($token) {
        $params['token'] = $token 
    }
    return (invoke-sumo -path "healthEvents" -method GET -session $sumo_session -v 'v1' -params $params)
}
 
<#
     .DESCRIPTION
     /v1/healthEvents/resources,post
 
     .PARAMETER sumo_session
     Specify a session, defaults to $sumo_session
 
     .PARAMETER body
     PSCustomObject body for post

    .PARAMETER limit
    rows to return max 1000

    .PARAMETER token
     Continuation token to get the next page of results. A page object with the next continuation token is returned in the response body. Subsequent GET requests should specify the continuation token to get the next page of results

    .EXAMPLE
     Get-HealthEventResources -sumo_session $be -body @{'data'=@(@{'id'='00000000234561C1'; 'name'='sumo'; 'type'='Source';})}
 
    .OUTPUTS
     PSCustomObject.
 #>
 
 
function Get-HealthEventResources {
 
    Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory = $True)]$body,
        [parameter()][string] $limit,
        [parameter()][string] $token
    )
    $params = @{}

    if ($limit) {
        $params['limit'] = $limit
    }
    if ($token) {
        $params['token'] = $token 
    }

    return (invoke-sumo -path "healthEvents/resources" -method POST -session $sumo_session -v 'v1' -body $body -params $params)
}
 
 