# auto generated by srcgen apps 11/17/2020 2:22:04 PM 


<#
    .DESCRIPTION
    /v1/apps,get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .OUTPUTS
    PSCustomObject.
#>


function Get-Apps {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session
    )
    return (invoke-sumo -path "apps" -method GET -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/apps/install/{jobId}/status,get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER jobId
    jobId for get

    .OUTPUTS
    PSCustomObject.
#>


function Get-AppInstallStatusById {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$jobId
    )
    return (invoke-sumo -path "apps/install/$jobId/status" -method GET -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/apps/{uuid},get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER uuid
    uuid for get

    .OUTPUTS
    PSCustomObject.
#>


function Get-AppById {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$uuid
    )
    return (invoke-sumo -path "apps/$uuid" -method GET -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/apps/{uuid}/install,post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER uuid
    uuid for post

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function New-AppInstallById {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$uuid,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "apps/$uuid/install" -method POST -session $sumo_session -v 'v1' -body $body )
}

