# auto generated by srcgen healthEvents 11/13/2020 3:29:44 PM 


<#
    .DESCRIPTION
    /v1/healthEvents,get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .OUTPUTS
    PSCustomObject.
#>


function Get-HealthEvent {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session
    )
    return (invoke-sumo -path "healthEvents" -method GET -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/healthEvents/resources,post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function New-HealthEventsResource {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "healthEvents/resources" -method POST -session $sumo_session -v 'v1' -Body ($body | ConvertTo-Json) )
}

