# auto generated by srcgen logSearches 11/13/2020 3:29:44 PM 


<#
    .DESCRIPTION
    /v1/logSearches/estimatedUsage,post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function New-LogSearchesEstimatedUsage {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "logSearches/estimatedUsage" -method POST -session $sumo_session -v 'v1' -Body ($body | ConvertTo-Json) )
}

