# auto generated by srcgen metricsQueries 12/8/2021 1:02:02 PM 


<#
    .DESCRIPTION
    /v1/metricsQueries,post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function New-MetricsQueries {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "metricsQueries" -method POST -session $sumo_session -v 'v1' -body $body )
}

