# auto generated by srcgen passwordPolicy 12/8/2021 1:02:03 PM 


<#
    .DESCRIPTION
    /v1/passwordPolicy,get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .OUTPUTS
    PSCustomObject.
#>


function Get-PasswordPolicy {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session
    )
    return (invoke-sumo -path "passwordPolicy" -method GET -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/passwordPolicy,put

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER body
    PSCustomObject body for put

    .OUTPUTS
    PSCustomObject.
#>


function Set-PasswordPolicy {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "passwordPolicy" -method PUT -session $sumo_session -v 'v1' -body $body )
}

