# auto generated by srcgen saml 11/17/2020 2:22:05 PM 


<#
    .DESCRIPTION
    /v1/saml/identityProviders,get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .OUTPUTS
    PSCustomObject.
#>


function Get-SamlIdentityProviders {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session
    )
    return (invoke-sumo -path "saml/identityProviders" -method GET -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/saml/identityProviders,post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function New-SamlIdentityProviders {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "saml/identityProviders" -method POST -session $sumo_session -v 'v1' -body $body )
}

<#
    .DESCRIPTION
    /v1/saml/identityProviders/{id},delete

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER id
    id for delete

    .OUTPUTS
    PSCustomObject.
#>


function Delete-SamlIdentityProvidersById {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$id
    )
    return (invoke-sumo -path "saml/identityProviders/$id" -method DELETE -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/saml/identityProviders/{id},put

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER id
    id for put

    .PARAMETER body
    PSCustomObject body for put

    .OUTPUTS
    PSCustomObject.
#>


function Set-SamlIdentityProvidersById {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$id,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "saml/identityProviders/$id" -method PUT -session $sumo_session -v 'v1' -body $body )
}

<#
    .DESCRIPTION
    /v1/saml/lockdown/disable,post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function Set-SamlLockdownDisable {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "saml/lockdown/disable" -method POST -session $sumo_session -v 'v1' -body $body )
}

<#
    .DESCRIPTION
    /v1/saml/lockdown/enable,post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function Set-SamlLockdownEnable {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "saml/lockdown/enable" -method POST -session $sumo_session -v 'v1' -body $body )
}

<#
    .DESCRIPTION
    /v1/saml/whitelistedUsers,get

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .OUTPUTS
    PSCustomObject.
#>


function Get-SamlWhitelistedUsers {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session
    )
    return (invoke-sumo -path "saml/whitelistedUsers" -method GET -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/saml/whitelistedUsers/{userId},delete

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER userId
    userId for delete

    .OUTPUTS
    PSCustomObject.
#>


function Delete-SamlWhitelistedUserById {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$userId
    )
    return (invoke-sumo -path "saml/whitelistedUsers/$userId" -method DELETE -session $sumo_session -v 'v1')
}

<#
    .DESCRIPTION
    /v1/saml/whitelistedUsers/{userId},post

    .PARAMETER sumo_session
    Specify a session, defaults to $sumo_session

    .PARAMETER userId
    userId for post

    .PARAMETER body
    PSCustomObject body for post

    .OUTPUTS
    PSCustomObject.
#>


function New-SamlWhitelistedUserById {

   Param(
        [parameter()][SumoAPISession]$sumo_session = $sumo_session,
        [parameter(mandatory=$True)]$userId,
        [parameter(mandatory=$True)]$body
    )
    return (invoke-sumo -path "saml/whitelistedUsers/$userId" -method POST -session $sumo_session -v 'v1' -body $body )
}

